set(_AMENT_PACKAGE_NAME "chapt2")
set(chapt2_VERSION "0.0.0")
set(chapt2_MAINTAINER "bei <bei@todo.todo>")
set(chapt2_BUILD_DEPENDS "rclcpp" "rclpy")
set(chapt2_BUILDTOOL_DEPENDS "ament_cmake")
set(chapt2_BUILD_EXPORT_DEPENDS "rclcpp" "rclpy")
set(chapt2_BUILDTOOL_EXPORT_DEPENDS )
set(chapt2_EXEC_DEPENDS "rclcpp" "rclpy")
set(chapt2_TEST_DEPENDS )
set(chapt2_GROUP_DEPENDS )
set(chapt2_MEMBER_OF_GROUPS )
set(chapt2_DEPRECATED "")
set(chapt2_EXPORT_TAGS)
list(APPEND chapt2_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
